In [48]:
# Import necessary libraries
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report
import os
import cv2




In [22]:


# Load your dataset
# Assume you have a CSV file with features and labels
# Replace 'your_dataset.csv' with the actual filename
data = pd.read_csv('full_df.csv')



In [19]:
# Import necessary libraries
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

In [32]:
# Drop unnecessary columns
columns_to_drop = ['ID', 'Left-Fundus', 'Right-Fundus', 'Left-Diagnostic Keywords', 
                   'Right-Diagnostic Keywords', 'labels', 'target', 'filename']

X = data.drop(columns=columns_to_drop, axis=1)  # Features
y = data['labels']  # Labels



In [27]:
# Identify categorical columns
categorical_columns = ['Patient Sex']

In [33]:
# One-hot encode categorical columns
X= pd.get_dummies(X, columns=categorical_columns)


In [63]:
# Drop any remaining non-numeric columns
X = X.select_dtypes(include='number')

In [64]:
# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


In [97]:
# Create a Random Forest Classifier
rf_classifier = RandomForestClassifier(n_estimators=100, random_state=56)

In [98]:
# Function to load and preprocess images
def load_images(folder):
    images = []
    labels = []
    for filename in os.listdir(folder):
        img = cv2.imread(os.path.join(folder, filename))
        if img is not None:
            # Assuming images are of fixed size, you may need to resize them
            img = cv2.resize(img, (64, 64))
            images.append(img.flatten())  # Flatten the image into a 1D array
            labels.append(int(filename.split('_')[0]))  # Assuming the label is in the filename
    return np.array(images), np.array(labels)

In [99]:
# Path to your training and testing datasets
train_path = r"C:\Users\PMLS\Downloads\FYP DR kaggle\Mishkaat\Training_images"
test_path = r"C:\Users\PMLS\Downloads\FYP DR kaggle\Mishkaat\Testing_images"


In [100]:
# Load and preprocess training images
X_train, y_train = load_images(train_path)


In [101]:
# Load and preprocess testing images
X_test, y_test = load_images(test_path)

In [105]:
# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=56)

In [106]:
# Create a Random Forest Classifier
rf_classifier = RandomForestClassifier(n_estimators=100, random_state=56)

In [107]:

# Train the classifier
rf_classifier.fit(X_train, y_train)

RandomForestClassifier(random_state=56)

In [73]:
# Make predictions on the test set
y_pred = rf_classifier.predict(X_test)

In [74]:
# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy:.2f}")

Accuracy: 0.79


In [75]:
# Display the classification report
print("Classification Report:")
print(classification_report(y_test, y_pred))

Classification Report:
              precision    recall  f1-score   support

       ['A']       0.81      0.93      0.87        46
       ['C']       0.70      0.84      0.77        58
       ['D']       0.78      0.92      0.84       333
       ['G']       0.79      0.85      0.82        61
       ['H']       0.79      0.82      0.81        28
       ['M']       0.77      0.96      0.85        48
       ['N']       0.92      0.72      0.81       569
       ['O']       0.47      0.57      0.52       136

    accuracy                           0.79      1279
   macro avg       0.75      0.83      0.79      1279
weighted avg       0.81      0.79      0.79      1279



In [79]:
# Print the results
print("Accuracy:", accuracy)


Accuracy: 0.7873338545738858


In [83]:
# Import necessary libraries
from sklearn.metrics import confusion_matrix



In [85]:
# Calculate and display the confusion matrix
conf_matrix = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(conf_matrix)

Confusion Matrix:
[[ 43   0   1   0   1   0   1   0]
 [  0  49   3   0   0   0   0   6]
 [  4   5 306   2   3   2   0  11]
 [  1   0   0  52   1   0   4   3]
 [  0   0   5   0  23   0   0   0]
 [  0   0   1   0   0  46   1   0]
 [  5  11  58  11   0   7 410  67]
 [  0   5  18   1   1   5  28  78]]


Confusion Matrix:
 [[ 43   0   1   0   1   0   1   0]
 [  0  49   3   0   0   0   0   6]
 [  4   5 306   2   3   2   0  11]
 [  1   0   0  52   1   0   4   3]
 [  0   0   5   0  23   0   0   0]
 [  0   0   1   0   0  46   1   0]
 [  5  11  58  11   0   7 410  67]
 [  0   5  18   1   1   5  28  78]]


In [90]:

print("Shape of X_train:", X_train.shape)
print("Shape of y_train:", y_train.shape)
print("Shape of X_test:", X_test.shape)
print("Shape of y_test:", y_test.shape)

Shape of X_train: (5113, 9)
Shape of y_train: (5113,)
Shape of X_test: (1279, 9)
Shape of y_test: (1279,)


In [91]:
import joblib

In [96]:

# Save the trained model to a file
model_filename = 'rforest.joblib'
joblib.dump(rf_classifier, model_filename)

['rforest.joblib']